# Generated by Django 3.0.2 on 2020-01-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_employee_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Timestamp',
            field=models.DateTimeField(default=None),
        ),
    ]
